runtime: nodejs18

env_variables:
  MONGODB_URI: "MONGODB_URI=mongodb+srv://bh00fie:CapraGialla13!@coverlettergenerator.djrbtse.mongodb.net/?retryWrites=true&w=majority&appName=coverLetterGenerator"
  JWT_SECRET: "test123"

handlers:
  - url: /.*
    script: auto